### ISSUE TITLE
Issue #1 for the library project

### ISSUE THREAD

**Issue by eliasecasta** [mikethreels/library#2]
Hello Michael, your project looks really nice! The only detail that I want to mention you is the one we talked about in the morning:

- Don't look for negative IDs! 

Haha, I don't know if you had some dark magic happening in your app but I hope that by removing that line your app is still working as expected, HAPPY CODING, WAAAAAAAARRRRRRRRRRMMMMMMMMMM!!!!

**Comment by mikethreels** [comment]
thanks Elias, the issue has been resolved
